#!/usr/bin/env python3

"""
Botan CI feature macro check script

(C) 2026 Jack Lloyd

Botan is released under the Simplified BSD License (see license.txt)

A misspelled feature macro inside a preprocessor conditional does not cause a
compile error; the branch just silently never gets built. This script checks
that every BOTAN_ macro referenced in an #if/#ifdef/#ifndef/#elif line in the
source tree is one that could actually be defined by some build, namely one of:

 - a macro generated by configure.py from the OS/arch/compiler/module
   descriptions in src/build-data (BOTAN_TARGET_OS_IS_*, BOTAN_TARGET_OS_HAS_*,
   BOTAN_TARGET_ARCH_IS_*, BOTAN_TARGET_ARCH_SUPPORTS_*, BOTAN_BUILD_COMPILER_IS_*,
   BOTAN_HAS_*, ...)
 - a macro defined literally in one of the build.h/target_info.h templates
 - a macro defined by a #define somewhere in the source tree
 - a small allowlist of macros provided by the build command line or by users

It also checks that conditional dependencies in module info.txt files
(eg "arm64?cpuid_aarch64") name a known architecture or OS feature, since
configure.py does not validate these and a typo there silently drops the
dependency.
"""

import argparse
import difflib
import os
import re
import sys

# Macros that are legitimately defined outside of the source tree and the
# configure.py templates.
EXTERNALLY_DEFINED_MACROS = {
    # Passed on the compiler command line by the generated makefile
    'BOTAN_IS_BEING_BUILT',
    # Set by users before including Botan headers
    'BOTAN_NO_DEPRECATED_WARNINGS',
    # Header guard of the amalgamation header written by configure.py
    'BOTAN_AMALGAMATION_H_',
}

# Values accepted by configure.py options which are turned into macros
FUZZER_TYPES = ['libfuzzer', 'afl', 'klee', 'test']
CT_VALUE_BARRIER_TYPES = ['asm', 'volatile', 'none']

# Suffixes of files scanned for macro usage
SOURCE_SUFFIXES = ('.cpp', '.h', '.c')

BOTAN_MACRO_RE = re.compile(r'\bBOTAN_[A-Za-z0-9_]+')
PREPROC_COND_RE = re.compile(r'^\s*#\s*(?:if|ifdef|ifndef|elif|elifdef|elifndef)\b(.*)$')
PREPROC_DEFINE_RE = re.compile(r'^\s*#\s*define\s+(BOTAN_[A-Za-z0-9_]+)')
TEMPLATE_DEFINE_RE = re.compile(r'^\s*#\s*define\s+(BOTAN_[A-Z0-9_]+)(?:\s|$)')
BLOCK_START_RE = re.compile(r'^<([a-z_:]+)>$')
BLOCK_END_RE = re.compile(r'^</([a-z_:]+)>$')
KEY_VALUE_RE = re.compile(r'^([a-zA-Z0-9_]+)\s+(.*)$')


def parse_info_file(path):
    """
    Minimal parser for the build-data/info.txt format. Returns a tuple of
    (top-level key -> value dict, block name -> list of lines dict). Lines
    inside blocks are returned verbatim (comments and blanks removed).
    """
    keys = {}
    blocks = {}
    current = None

    with open(path, encoding='utf8') as f:
        for line in f:
            line = line.split('#', 1)[0].strip()
            if not line:
                continue

            start = BLOCK_START_RE.match(line)
            end = BLOCK_END_RE.match(line)

            if start:
                current = start.group(1)
                blocks.setdefault(current, [])
            elif end:
                current = None
            elif current is not None:
                blocks[current].append(line)
            else:
                kv = KEY_VALUE_RE.match(line)
                if kv:
                    keys[kv.group(1)] = kv.group(2).strip()

    return keys, blocks


def basenames(directory):
    return [f[:-4] for f in sorted(os.listdir(directory)) if f.endswith('.txt')]


def collect_build_data(root):
    """
    Returns a dictionary describing everything in src/build-data that
    configure.py could turn into a macro.
    """
    build_data = os.path.join(root, 'src', 'build-data')

    info = {
        'os_names': [],
        'os_features': set(),
        'arch_names': [],
        'arch_families': set(),
        'isa_extensions': set(),
        'cc_macros': set(),
        'sanitizers': set(),
        'module_defines': set(),
        'module_conditions': [],  # (info.txt path, condition)
        'module_references': set(),  # names of OS features, ISAs, archs, compilers used by info.txt files
    }

    os_dir = os.path.join(build_data, 'os')
    for os_name in basenames(os_dir):
        _, blocks = parse_info_file(os.path.join(os_dir, os_name + '.txt'))
        info['os_names'].append(os_name)
        info['os_features'].update(blocks.get('target_features', []))

    arch_dir = os.path.join(build_data, 'arch')
    for arch_name in basenames(arch_dir):
        keys, blocks = parse_info_file(os.path.join(arch_dir, arch_name + '.txt'))
        info['arch_names'].append(arch_name)
        if 'family' in keys:
            info['arch_families'].add(keys['family'])
        info['isa_extensions'].update(blocks.get('isa_extensions', []))

    cc_dir = os.path.join(build_data, 'cc')
    for cc_name in basenames(cc_dir):
        keys, blocks = parse_info_file(os.path.join(cc_dir, cc_name + '.txt'))
        if 'macro_name' in keys:
            info['cc_macros'].add(keys['macro_name'])
        for line in blocks.get('sanitizers', []):
            info['sanitizers'].add(line.split('->', 1)[0].strip())

    for dirpath, _, filenames in os.walk(os.path.join(root, 'src', 'lib')):
        if 'info.txt' not in filenames:
            continue
        path = os.path.join(dirpath, 'info.txt')
        _, blocks = parse_info_file(path)
        for block in ['defines', 'internal_defines']:
            for line in blocks.get(block, []):
                info['module_defines'].add(line.split('->', 1)[0].strip())
        for line in blocks.get('requires', []):
            if '?' in line:
                cond = line.split('?', 1)[0]
                info['module_conditions'].append((path, cond))
                info['module_references'].add(cond)
        for line in blocks.get('os_features', []):
            info['module_references'].update(line.split(','))
        for line in blocks.get('isa', []):
            # Either "isa" or "arch:isa"
            info['module_references'].update(line.split(':'))
        for line in blocks.get('arch', []):
            info['module_references'].add(line)
        for line in blocks.get('cc', []):
            # Either "cc", "!cc" or "cc:min_version"
            info['module_references'].add(line.lstrip('!').split(':', 1)[0])

    return info


def macros_from_build_data(info):
    macros = set()

    macros.update('BOTAN_TARGET_OS_IS_' + n.upper() for n in info['os_names'])
    macros.update('BOTAN_TARGET_OS_HAS_' + n.upper() for n in info['os_features'])
    macros.update('BOTAN_TARGET_ARCH_IS_' + n.upper() for n in info['arch_names'])
    macros.update('BOTAN_TARGET_ARCH_IS_%s_FAMILY' % (n.upper()) for n in info['arch_families'])
    macros.update('BOTAN_TARGET_ARCH_SUPPORTS_' + n.upper() for n in info['isa_extensions'])
    macros.update('BOTAN_BUILD_COMPILER_IS_' + n for n in info['cc_macros'])
    macros.update('BOTAN_HAS_SANITIZER_' + n.upper() for n in info['sanitizers'])
    macros.update('BOTAN_HAS_' + n for n in info['module_defines'])
    macros.update('BOTAN_FUZZER_IS_' + n.upper() for n in FUZZER_TYPES)
    macros.update('BOTAN_CT_VALUE_BARRIER_USE_' + n.upper() for n in CT_VALUE_BARRIER_TYPES)

    return macros


def macros_from_templates(root):
    """
    Macros defined verbatim (not via a %{...} substitution) in the header
    templates that configure.py fills in.
    """
    macros = set()
    template_dir = os.path.join(root, 'src', 'build-data')

    for filename in sorted(os.listdir(template_dir)):
        if not filename.endswith('.in'):
            continue
        with open(os.path.join(template_dir, filename), encoding='utf8') as f:
            for line in f:
                match = TEMPLATE_DEFINE_RE.match(line)
                if match:
                    macros.add(match.group(1))

    return macros


def source_files(root):
    for subdir in ['src']:
        for dirpath, dirnames, filenames in os.walk(os.path.join(root, subdir)):
            # Test data contains no code
            dirnames[:] = [d for d in dirnames if d != 'data']
            for filename in sorted(filenames):
                if filename.endswith(SOURCE_SUFFIXES):
                    yield os.path.join(dirpath, filename)


def logical_lines(path):
    """
    Yields (line number, line) with backslash continuations joined
    """
    with open(path, encoding='utf8', errors='replace') as f:
        pending = None
        pending_lineno = 0
        for lineno, line in enumerate(f, 1):
            line = line.rstrip('\n')
            if pending is not None:
                pending += ' ' + line
            else:
                pending = line
                pending_lineno = lineno

            if pending.endswith('\\'):
                pending = pending[:-1]
                continue

            yield pending_lineno, pending
            pending = None

        if pending is not None:
            yield pending_lineno, pending


def strip_comments(line):
    line = re.sub(r'/\*.*?\*/', ' ', line)
    return line.split('//', 1)[0]


def scan_sources(root):
    """
    Returns (defined macros, list of (path, line number, macro) uses in
    preprocessor conditionals)
    """
    defined = set()
    uses = []

    for path in source_files(root):
        for lineno, line in logical_lines(path):
            define = PREPROC_DEFINE_RE.match(line)
            if define:
                defined.add(define.group(1))
                continue

            cond = PREPROC_COND_RE.match(line)
            if cond:
                for macro in BOTAN_MACRO_RE.findall(strip_comments(cond.group(1))):
                    uses.append((path, lineno, macro))

    return defined, uses


def suggestion(macro, known):
    close = difflib.get_close_matches(macro, known, n=1, cutoff=0.8)
    if close:
        return " (did you mean %s?)" % (close[0])
    return ""


def check_macro_uses(root, info):
    known = set()
    known.update(macros_from_build_data(info))
    known.update(macros_from_templates(root))
    known.update(EXTERNALLY_DEFINED_MACROS)

    defined_in_source, uses = scan_sources(root)
    known.update(defined_in_source)

    errors = []
    for (path, lineno, macro) in uses:
        if macro not in known:
            errors.append("%s:%d: unknown feature macro %s%s" % (
                os.path.relpath(path, root), lineno, macro, suggestion(macro, known)))

    return errors, uses


def check_module_conditions(root, info):
    """
    Conditional requirements like "arm64?cpuid_aarch64" match either an
    architecture name or an OS feature; anything else silently never matches.
    """
    valid = set(info['arch_names']) | info['os_features']
    errors = []
    for (path, cond) in info['module_conditions']:
        if cond not in valid:
            errors.append("%s: unknown condition '%s' in <requires>%s" % (
                os.path.relpath(path, root), cond, suggestion(cond, valid)))
    return errors


def report_unused(info, uses):
    """
    Lists build-data entries that neither a preprocessor conditional nor a
    module info.txt refers to. This is informational; some entries are
    consumed only by configure.py itself.
    """
    used = {macro for (_, _, macro) in uses}
    referenced = info['module_references']

    def unused(prefix, names, suffix=''):
        return sorted(n for n in names if (prefix + n.upper() + suffix) not in used and n not in referenced)

    for (label, items) in [
            ('OS names', unused('BOTAN_TARGET_OS_IS_', info['os_names'])),
            ('OS features', unused('BOTAN_TARGET_OS_HAS_', info['os_features'])),
            ('architectures', unused('BOTAN_TARGET_ARCH_IS_', info['arch_names'])),
            ('architecture families', unused('BOTAN_TARGET_ARCH_IS_', info['arch_families'], '_FAMILY')),
            ('ISA extensions', unused('BOTAN_TARGET_ARCH_SUPPORTS_', info['isa_extensions'])),
            ('compilers', unused('BOTAN_BUILD_COMPILER_IS_', info['cc_macros'])),
    ]:
        if items:
            print("Unreferenced %s: %s" % (label, ' '.join(items)))


def main(argv=None):
    parser = argparse.ArgumentParser(description="Check that feature macros used in the source tree can exist")
    parser.add_argument('--root', default=os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'),
                        help='path to the repository root (default: relative to this script)')
    parser.add_argument('--report-unused', action='store_true',
                        help='also list build-data entries never referenced by a preprocessor conditional')
    args = parser.parse_args(argv)

    root = os.path.abspath(args.root)
    info = collect_build_data(root)

    errors, uses = check_macro_uses(root, info)
    errors += check_module_conditions(root, info)

    if args.report_unused:
        report_unused(info, uses)

    for error in errors:
        print("ERROR: %s" % (error))

    if errors:
        return 1

    print("Checked %d feature macro references" % (len(uses)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
