language: cpp
os: linux
dist: focal
compiler: gcc

jobs:
  include:
    - name: Coverage (GCC)
      env:
       - TARGET="coverage"
       - CCACHE_MAXSIZE=2G
       - PKCS11_LIB=/usr/lib/softhsm/libsofthsm2.so

    - name: Linux ppc64le (GCC)
      arch: ppc64le
      env:
       - TARGET="shared"

install:
  - ./src/scripts/ci/setup_travis.sh

script:
  - ./src/scripts/ci_build.py --os=$TRAVIS_OS_NAME --cc=$CC --cc-bin=$CXX --without-pylint3 --pkcs11-lib=$PKCS11_LIB $EXTRA_FLAGS $TARGET

# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master
    - release-2
    - coverity_scan

git:
  depth: 10

cache:
  ccache: true

addons:
  coverity_scan:
    project:
      name: "randombit/botan"
    notification_email: jack@randombit.net
    build_command_prepend: "./configure.py --no-optimizations --with-zlib --with-openssl"
    build_command: "make -j2"
    branch_pattern: coverity_scan
